CREATE TABLE ADMIN (
    ADMIN_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ADMIN_ID)
);


CREATE TABLE STUDENT (
    STUDENT_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DOB DATE,
    SMART_CARD_ID VARCHAR(50),
    PHONE VARCHAR(20),
    HOSTEL VARCHAR(100),
    BLOCK_UNTIL DATE,
    PRIMARY KEY (STUDENT_ID)
);


CREATE TABLE COUNSELOR (
    COUNSELOR_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    SPECIALIZATION VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COUNSELOR_ID)
);


CREATE TABLE FACULTY (
    FACULTY_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    SPECIALIZATION VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FACULTY_ID)
);


CREATE TABLE HOSTEL (
    ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    HOSTEL_NAME VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);


CREATE TABLE OTP_STORE (
    EMAIL VARCHAR(150) NOT NULL,
    OTP VARCHAR(6) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EMAIL)
);


CREATE TABLE APPOINTMENT (
    ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    STUDENT_ID INTEGER NOT NULL,
    COUNSELOR_ID INTEGER NOT NULL,
    APPOINTMENT_DATE DATE NOT NULL,
    TIME_SLOT VARCHAR(50) NOT NULL,
    PREFERRED_MODE VARCHAR(50),
    CHIEF_CONCERN VARCHAR(100),
    STATUS VARCHAR(30) DEFAULT 'SCHEDULED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MEETING_LINK VARCHAR(500),
    STUDENT_JOINED BOOLEAN DEFAULT FALSE,
    COUNSELOR_JOINED BOOLEAN DEFAULT FALSE,
    MEETING_START_TIME TIMESTAMP,

    PRIMARY KEY (ID),

    CONSTRAINT FK_STUDENT
        FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CONSTRAINT FK_COUNSELOR
        FOREIGN KEY (COUNSELOR_ID)
        REFERENCES COUNSELOR(COUNSELOR_ID)
);


CREATE TABLE COUNSELOR_TIMETABLE (
    ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    COUNSELOR_ID INTEGER NOT NULL,
    DAY VARCHAR(10) NOT NULL,
    TIME_SLOT VARCHAR(20) NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT FK_COUNSELOR_TT
        FOREIGN KEY (COUNSELOR_ID)
        REFERENCES COUNSELOR(COUNSELOR_ID)
);


CREATE TABLE FEEDBACK (
    FEEDBACK_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID INTEGER NOT NULL,
    USER_ROLE VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL,
    RATING INTEGER,
    SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_VISIBLE INTEGER DEFAULT 1,

    PRIMARY KEY (FEEDBACK_ID),

    CHECK (RATING BETWEEN 1 AND 5)
);


CREATE TABLE WORKSHOP (
    WORKSHOP_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITLE VARCHAR(150) NOT NULL,
    WORKSHOP_DATE DATE NOT NULL,
    WORKSHOP_TIME VARCHAR(20) NOT NULL,
    VENUE VARCHAR(150) NOT NULL,
    POSTED_BY_ROLE VARCHAR(30) NOT NULL,
    POSTED_BY_ID INTEGER NOT NULL,
    STATUS VARCHAR(30) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TEMPLATE_IMAGE BLOB(2147483647),

    PRIMARY KEY (WORKSHOP_ID),

    CHECK (POSTED_BY_ROLE IN ('FACULTY', 'COUNSELLOR'))
);


CREATE TABLE SESSION_NOTES (
    NOTE_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    APPOINTMENT_ID INTEGER NOT NULL UNIQUE,
    COUNSELOR_ID INTEGER,
    PROBLEMATIC_BEHAVIOR VARCHAR(2000),
    TARGETED_BEHAVIOR VARCHAR(2000),
    INTERVENTION VARCHAR(2000),
    RESPONSE VARCHAR(2000),
    PLAN VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FACULTY_ID INTEGER,

    PRIMARY KEY (NOTE_ID)
);


CREATE TABLE REFERRED_CASES (
    REFERRAL_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    APPOINTMENT_ID INTEGER NOT NULL,
    STUDENT_ID INTEGER NOT NULL,
    COUNSELOR_ID INTEGER NOT NULL,
    FACULTY_ID INTEGER NOT NULL,
    CHIEF_CONCERN VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(30) DEFAULT 'REFERRED',

    PRIMARY KEY (REFERRAL_ID),

    FOREIGN KEY (APPOINTMENT_ID)
        REFERENCES APPOINTMENT(ID),

    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    FOREIGN KEY (COUNSELOR_ID)
        REFERENCES COUNSELOR(COUNSELOR_ID),

    FOREIGN KEY (FACULTY_ID)
        REFERENCES FACULTY(FACULTY_ID)
);